### ISSUE TITLE
Introduce a parameter to enable/disable the plugin

### ISSUE THREAD

**Issue by grabnerandi** [dynatrace-oss/jmeter-dynatrace-plugin#1]
I would like to introduce a new parameter called "enable". The default can be true - but - I would like to use this parameter to enable/disable this extension via a JMeter parameter instead of having to enable/disable it through a JMX setting.

My use case is that we leverage JMeter with the open source project keptn (www.keptn.sh). When uploading a JMX File that contains that Dynatrace plugin I would like to enable/disable this extension via a parameter that Keptn passes to JMeter. This gives us more flexibility to control the behavior instead of having to upload different versions of the same JMX file

**Comment by christian-inzko-dt** [comment]
fixed with https://github.com/dynatrace-oss/jmeter-dynatrace-plugin/releases/tag/v1.2.snapshot
