### ISSUE TITLE
Publish Plugin on https://jmeter-plugins.org

### ISSUE THREAD

**Issue by jloisel** [dynatrace-oss/jmeter-dynatrace-plugin#11]
Which allows for easier management of jmeter plugins / automation (installing the plugin through command line using PluginsManager).

**Comment by jloisel** [comment]
Any update? Would allow to make it easier to install the plugin via automation (jmeter-plugins cmd line).

**Comment by christian-inzko-dt** [comment]
Hi @jloisel 
do you have an idea how to publish the plugin there (without adding the plugin code to this jmeter-plugin repo too?
I have checked there docs but tbh. i couldn't find out, how to add my plugin there'

**Comment by jloisel** [comment]
From what I understand, you need to create a pull request on jmeter-plugins repository, like they did for datadog:
https://github.com/undera/jmeter-plugins/pull/450

**Comment by christian-inzko-dt** [comment]
ok thanks, i will try it

**Comment by christian-inzko-dt** [comment]
@jloisel sorry, that it took so much time, but i was busy with other things

Extension of the PluginManager Repo - see https://github.com/undera/jmeter-plugins/pull/515

![Dynatrace_JMeter_Plugin](https://user-images.githubusercontent.com/71386416/154003601-0643c617-0f98-4ee4-9c12-e6675bc7860b.PNG)

**Comment by jloisel** [comment]
Thanks, that's great! :+1:
