### ISSUE TITLE
Plugin dependencies must have "provided" not "runtime" scope

### ISSUE THREAD

**Issue by jloisel** [dynatrace-oss/jmeter-dynatrace-plugin#12]
When we add the plugin as a maven dependency, it breaks our code (which needs JMeter dependencies like `ApacheJmeter_Core`:

```xml
    <dependency>
      <groupId>org.apache.jmeter</groupId>
      <artifactId>ApacheJMeter_http</artifactId>
      <scope>provided</scope>
    </dependency>
<!-- Breaks the module compilation when added -->
    <dependency>
      <groupId>com.datadoghq</groupId>
      <artifactId>jmeter-datadog-backend-listener</artifactId>
      <scope>runtime</scope>
    </dependency>
```

Datadog works fine as the plugin dependencies are correctly scoped as `provided`:
https://github.com/DataDog/jmeter-datadog-backend-listener

As of now, we're forced to add `ApacheJmeter_Core` as `provided` dependency to our `pom.xml` as a workaround to fix this issue:

```xml
    <dependency>
      <groupId>com.dynatrace.jmeter.plugins</groupId>
      <artifactId>jmeter-dynatrace-plugin</artifactId>
      <scope>runtime</scope>
    </dependency>
    <!-- Required due to dynatrace plugin "runtime" dependencies -->
    <dependency>
      <groupId>org.apache.jmeter</groupId>
      <artifactId>ApacheJMeter_core</artifactId>
      <version>${jmeter.version}</version>
      <scope>provided</scope>
    </dependency>
```

Please change the scope to `provided` instead of `runtime` to avoid breaking the compilation classpath of modules which need your plugin.

**Comment by christian-inzko-dt** [comment]
new version 1.8.0 published to maven repo which defines the jmeter dependencies as "provided"

**Comment by jloisel** [comment]
Thanks :+1:
