### ISSUE TITLE
400 error on plugin startup for first POST of metrics to the endpoint.

### ISSUE THREAD

**Issue by jukinner** [dynatrace-oss/jmeter-dynatrace-plugin#18]
I've implemented the plugin on my companies jmeter tests and everything seems to report properly during the test. 1 thing that I can't figure out is we consistently get a 400 error when the listener is starting up and configuring itself for the first time. 

In the Jmeter logs we get a WARN(ing) on the first time it submits: 
![image](https://user-images.githubusercontent.com/35537811/176235676-7c5999a1-a09c-4579-a242-fe49fc65038d.png)

Does this matter? Seems like a startup order issue. There are not metrics to send at that time. 

I've tried altering my payload and making small changes but no luck. Otherwise it works well and sends in the metrics for the rest of the test.

**Comment by grabnerandi** [comment]
Thats interesting. Yeah - could be that the plugin is making a call to the metrics/ingest API without any value during startup. Calling the API with 0 values I think leads to an HTTP 400 error. So - IMHO I think this error can be ignored - but - probably the plugin is making a call it doesnt need to make

**Comment by christian-inzko-dt** [comment]
yes, you're right, this initial request is not neccessary

**Comment by rpionke** [comment]
I fixed the error message in this PR https://github.com/dynatrace-oss/jmeter-dynatrace-plugin/pull/21
