### ISSUE TITLE
Add a sampler filter in the configuration

### ISSUE THREAD

**Issue by rpionke** [dynatrace-oss/jmeter-dynatrace-plugin#19]
**Is your feature request related to a problem? Please describe.**
Since we use protocol based testing with JMeter we have a lot of resources as test steps in our test plan. But only a few a necessary to report to Dynatrace.

**Describe the solution you'd like**
We would like to have the possibility to filter sampler names by regex as the InfluxDBListener does.

**Comment by christian-inzko-dt** [comment]
fixed in release 1.9
