### ISSUE TITLE
Dynatrace API Endpoint and Token Sanity Check before execution

### ISSUE THREAD

**Issue by grabnerandi** [dynatrace-oss/jmeter-dynatrace-plugin#2]
When passing in a wrong or invalid API Token or Dynatrace API Endpoint the plugin tries to call that invalid combination everytime it tries to send data. This results in a lot of error log outputs during a JMeter test execution that uses this plugin

I suggest that the plugin should do an initial check on whether the API is reachable using the passed Token. If that is not the case the plugin should create a single error log but then stop sending data as this data would never reach Dynatrace anyway

**Comment by christian-inzko-dt** [comment]
fixed with https://github.com/dynatrace-oss/jmeter-dynatrace-plugin/releases/tag/v1.2.snapshot
