### ISSUE TITLE
Dynatrace Metrics not matching with JMeter

### ISSUE THREAD

**Issue by QAInsights** [dynatrace-oss/jmeter-dynatrace-plugin#4]
I did a simple load test against my local app. I have found conflicts between the dynatrace metrics and JMeter metrics.

JMeter Summary Report
![QAInsights-0078](https://user-images.githubusercontent.com/2826376/103449394-c1363b80-4c9f-11eb-9d05-7c46a341a1c4.jpg)

Conflicting Metrics:

  | Transaction Name | JMeter | Dynatrace
-- | -- | -- | --
jmeter.usermetrics.transaction.maxtime | T00_HomePage | 1730 | 141
  | T10_TopCommand | 8029 | 429
jmeter.usermetrics.transaction.mintime | T00_HomePage | 5 | 5
  | T10_TopCommand | 7 | 8
jmeter.usermetrics.transaction.meantime: | T00_HomePage | 24 | 13.6
  | T10_TopCommand | 94 | 28.6
jmeter.usermetrics.transaction.receivedbytes | T00_HomePage | 355.14 KB/sec | 109mil
  | T10_TopCommand | 356.71 KB/sec | 109mil
jmeter.usermetrics.transaction.sentbytes | T00_HomePage | 1.86/s | 569k
  | T10_TopCommand | 2.087/s | 637k

**Comment by christian-inzko-dt** [comment]
ok thank you, i will check it

**Comment by christian-inzko-dt** [comment]
i am not sure that you can directly compare those values. The MintBackendListener is aggregating the values and sending the aggregated results every minute as MINT metrics to Dynatrace and based on the chart timeframe and settings which you use its maybe aggregated again. 
Did you use the newest release (1.3) of the plugin?
Have you tried to compare the results with another type of BackendListener?

**Comment by QAInsights** [comment]
Thanks @christian-inzko-dt, yes I did testing in 1.3 version. I will run the test with InfluxDB and Dynatrace and share the results today.

**Comment by QAInsights** [comment]
@christian-inzko-dt I tested with InfluxDB, the stats are almost matching in min, max and mean response time. But for the received and sent bytes, Dynatrace is showing in `mil`. Can we have the unit more clear?

**Comment by christian-inzko-dt** [comment]
Thanks for your testing with InfluxDB.
Currently its not possible, but the Dynatrace metrics explorer is still in "Early adopter" phase but i am quite sure it will be possible when its GA

**Comment by christian-inzko-dt** [comment]
I have checked with our metrics and explorer teams and it is planned to support additional meta info for the metrics so you can specify the type of the data (e.g, "kB", "MB", "ms") and also display those types in the charts. As soon this is available i will also send this meta info in this plugin.

**Comment by christian-inzko-dt** [comment]
@QAInsights  If this is ok for you i will close the issue?

**Comment by QAInsights** [comment]
Sure, let me do more runs in the next release :)
