### ISSUE TITLE
MintMetricSender.checkConnection has short timeout and does not log error nicely

### ISSUE THREAD

**Issue by xoffey** [dynatrace-oss/jmeter-dynatrace-plugin#5]
I was getting many errors like this:
2021-01-16 00:07:24,990 INFO c.d.j.p.MintBackendListener: Start MINT metric sender for url https://zzzz.live.dynatrace.com/api/v2/metrics/ingest failed with General Error executing connection check for MINT server, setting enabled state to false

I tracked it down to a lastRequest.get() call in MintMetricSender.checkConnection() that has a timeout of only 1 second. By changing the timeout to 30 seconds, I am able to avoid the errors.

Also, unless I set loglevel to DEBUG, it doesn't tell me that it is a timeout.

The exception-catching code looks like this
```
		catch (ExecutionException | TimeoutException | InterruptedException ex) {
			log.debug("Error executing connection check for MINT server", ex);
			throw new MintConnectionException("General Error executing connection check for MINT server");
		}
```
I would suggest you log.warn, or log.error, the exception type, And of course, make the timeout longer.

Thanks for your efforts!

**Comment by christian-inzko-dt** [comment]
fixed with version 1.4
