### ISSUE TITLE
jmeter-dynatrace-plugin is not available in maven repo

### ISSUE THREAD

**Issue by girishmanyam** [dynatrace-oss/jmeter-dynatrace-plugin#7]
Would it be possible to get this library to published into maven repo ?. so it will be integrated the maven and Jmeter

**Comment by christian-inzko-dt** [comment]
thank you for your suggestion - i will check this
can you please explain me, what is your use case for this?

**Comment by girishmanyam** [comment]
my use case is to download this jar into Jmeter lib/ext using maven-jmeter-plugin.

**Comment by christian-inzko-dt** [comment]
ok
i am working on this publishing to maven repo

**Comment by christian-inzko-dt** [comment]
fixed with  release 1.7
Maven URL: https://search.maven.org/artifact/com.dynatrace.jmeter.plugins/jmeter-dynatrace-plugin/1.7.0/jar
