### ISSUE TITLE
meter.usermetrics.transaction.maxtime graph values aren't populated correctly

### ISSUE THREAD

**Issue by girishmanyam** [dynatrace-oss/jmeter-dynatrace-plugin#8]
![Screenshot 2021-03-12 at 10 11 09](https://user-images.githubusercontent.com/2779562/110925696-6b26e980-831b-11eb-9f07-57ff2186f6e0.png)

![Screenshot 2021-03-12 at 10 15 49](https://user-images.githubusercontent.com/2779562/110926131-ed171280-831b-11eb-9652-2f1f30101214.png)

From the graph we can see the metric captured are in K and they are not in seconds. Also these values are not matching with Jmeter html report. 

Is this something can be looked into this issue.

**Comment by christian-inzko-dt** [comment]
I have checked with our metrics and explorer teams and it is planned to support additional meta info for the metrics so you can specify the type of the data (e.g, "kB", "MB", "ms") and also display those types in the charts. As soon this is available i will also send this meta info in this plugin.

Can you pls provide an example of the not matching values or explain how big is the difference?

**Comment by girishmanyam** [comment]
@christian-inzko-dt  Did you get a chance to look into above defect to show response times metrics in seconds rather than. KB please ? .

look like these below metrics returns in double that needs to converted to ms or s  (guess)

> addMetricLineForTransaction(transaction, "jmeter.usermetrics.transaction.mintime", metric.getAllMinTime());
> addMetricLineForTransaction(transaction, "jmeter.usermetrics.transaction.maxtime", metric.getAllMaxTime());
> addMetricLineForTransaction(transaction, "jmeter.usermetrics.transaction.meantime", metric.getAllMean());

Without the above fix these transactional metrics are no use to monitor in Dynatrace
example :
- jmeter.usermetrics.transaction.mintime: 
- jmeter.usermetrics.transaction.maxtime:

Please let me know if you need more info these

**Comment by christian-inzko-dt** [comment]
Yes, its now possible to add metadata to the metrics in Dynatrace.
e.g.
![image](https://user-images.githubusercontent.com/71386416/141931515-ad057539-d69a-40b1-a842-36a46ba0eab7.png)
![image](https://user-images.githubusercontent.com/71386416/141931614-37cb897d-96ba-43b1-9732-3d627acbd6a8.png)

than you get
![image](https://user-images.githubusercontent.com/71386416/141931748-0096bced-d071-47a2-86cf-c7ac543b3869.png)

I have found no practicable way to do this automatically in the plugin, but you only have to do this once manually for those metrics.

Best regards,
Christian

**Comment by girishmanyam** [comment]
thanks. @christian-inzko-dt

**Comment by christian-inzko-dt** [comment]
@girishmanyam  does this work in your environment fulfil your needs? If yes, i will close this ticket?

**Comment by christian-inzko-dt** [comment]
seems to be fixed
